config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/about', to: 'pages#about'
  get '/help', to: 'pages#help'
  resources :todos
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord      ## will be ActiveRecord::Base in older Rails versions
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def hello
    render plain: "Hello, Bob!"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController    ## defining classes = CamelCase
  def home                                       ## defining methods = snake_case
    ## Nothing here!
  end

  def about
  end

  def help
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]   ## find Todo items

  def show 
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save                                        ## if the save is successful
      flash[:notice] = 'Your To-Do item was successfully created!'  ## add msg to flash
      redirect_to todo_path(@todo)                       ## use prefix for todos#show
    else                                                 ## if the save is unsuccessful
      render 'new'                                       ## show same form if db refuses
    end
  end
  
  def edit
  end

  def update
    if @todo.update(todo_params)           ## update DB entry
      flash[:notice] = 'Your To-Do item was successfully updated!'
      redirect_to todo_path(@todo)         ## redirect to show view if successful
    else
      render 'edit'                        ## show same form w/ errs if update unsuccessful
    end  
  end

  def index
    @todos = Todo.all                           ## simply grab all of the Todo items
  end

  def destroy
    @todo.destroy                                       ## remove entry from DB as learned
    flash[:notice] = 'Successfully deleted To-Do item'  ## notify user
    redirect_to todos_path                              ## go back to the To-Do list
  end

  private                                                ## THIS CONTROLLER ONLY
    def todo_params
      params.require(:todo).permit(:name, :description)  ## whitelisting params fields
    end

    def set_todo
      @todo = Todo.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |k, msg| %>          <!-- iterating a Hash, so specify key and val vars -->
  <ul>
    <li><%= msg %></li>
  </ul>
<% end %>

app/views/layouts/_navigation.html.erb
<div align="center">
  <h1> ToDoApp </h1>
  <h4>
    <%= link_to 'Home', root_path %>
    | <%= link_to 'My To-Do List', todos_path %> <!-- again using route prefix and _path -->
    | <%= link_to 'About', about_path %>
    | <%= link_to 'Help', help_path %>
  </h4>
  <hr />
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RorguideTodoapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>    <!-- don't have to include _ prefix here! -->
    <%= render 'layouts/messages' %>      <!-- no need to specify file type either! -->

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div align="center">
  <h2> About Us </h2>
  <div> <p>
      Clever and sophisticated individuals, creating order and harmony via the medium of To-Do entries (which we will mark off of our own to-do list!)
  </p></div>
</div>

app/views/pages/help.html.erb
<div align="center">
  <h2> Help </h2>
  <div>
    <p> No help for you. </p>
  </div>
</div>

app/views/pages/home.html.erb
<div align="center">
  <h2> Welcome to the Mighty To-Do App </h2>
  <h3> Where all your Tos become Doed </h3>
</div>

app/views/todos/_form.html.erb
<% if @todo.errors.any? %>                             <!-- check if any errors present -->
  <h3> Your To-Do item could not be saved: </h3>      <!-- if yes, display the messages -->
  <ul>
    <% @todo.errors.full_messages.each do |msg| %>      <!-- for all @todo err messages -->
      <li> <%= msg %> </li>                                <!-- display message in list -->
    <% end %>
  </ul>
<% end %>

<%= form_with model: @todo do |td_form| %>    <!-- using '=' erb tag as we're inserting -->

  <div>
    <%= td_form.label       :name %>             <!-- specifying form field & its value -->
    <br />
    <%= td_form.text_field  :name %>          
  </div>

  <div>
    <%= td_form.label     :description %>               <!-- label of description field -->
    <br />
    <%= td_form.text_area :description %>                <!-- area to enter description -->
  </div>

  <div>
    <%= td_form.submit %>                          <!-- submit the data to @td variable -->
  </div>

<% end %>                                                       <!-- end the Ruby block -->

app/views/todos/edit.html.erb
<div align="center">
  <h3> Edit To-Do item: <%= @todo.id.to_s %> </h3>

  <% if @todo.errors.any? %>                              <!-- check if any errors present -->
    <h3> Your To-Do item could not be saved: </h3>       <!-- if yes, display the messages -->
    <ul>
      <% @todo.errors.full_messages.each do |msg| %>       <!-- for all @todo err messages -->
        <li> <%= msg %> </li>                                 <!-- display message in list -->
      <% end %>
    </ul>
  <% end %>


  <%= form_with model: @todo do |td_form| %>   <!-- using '=' erb tag as we're inserting -->

    <div>
      <%= td_form.label       :name %>            <!-- specifying form field & its value -->
      <br />
      <%= td_form.text_field  :name %>          
    </div>

    <div>
      <%= td_form.label     :description %>              <!-- label of description field -->
      <br />
      <%= td_form.text_area :description %>               <!-- area to enter description -->
    </div>

    <div>
      <%= td_form.submit %>                         <!-- submit the data to @td variable -->
    </div>

  <% end %>                                                      <!-- end the Ruby block -->

  <p>
    <%= link_to 'Back to To-Do item', todo_path(@todo) %>                <!-- #show link -->
    |  <%= link_to 'Back to To-Do list', todos_path %>                  <!-- #index link -->
    | <%=
      link_to 'Delete this item',
      todo_path(@todo),
      method: :delete,
      data: {confirm: 'Are you sure?'}
    %>
  </p>
</div>

app/views/todos/index.html.erb
<div align="center">
  <h3> Your To-Do items: </h3>

  <table border=1>                                       <!-- create table with a border -->
    <tr>
      <th> ID </th>                              <!-- give the table appropriate headers -->
      <th> Name </th>
      <th> Description </th>
    </tr>
    <% @todos.each do |todo| %>                          <!-- array passed by controller -->
      <tr>                                                  <!-- new row per Todo object --> 
        <td> <%= todo.id.to_s %> </td>                      <!-- insert values of object -->
        <td> <%= link_to todo.name, todo_path(todo) %> </td>     <!-- link name to #show -->
        <td> <%= todo.description %> </td>
        <td> <%= link_to 'Show', todo_path(todo) %> </td>      <!-- pass todo var as arg -->
        <td> <%= link_to 'Edit', edit_todo_path(todo) %> </td>      <!-- #edit view link -->
        <td>
          <%=                                            ## insert embedded ruby
            link_to 'Delete',                            ## link text
            todo_path(todo),                             ## pass the #show URI pattern
            method: :delete,                             ## specify the method (verb) to use
            data: {confirm: 'Are you sure?'}             ## add confirmation prompt and text
            %>                                                 <!-- end erb block -->
        </td>
      </tr>
    <% end %>                                                    <!-- end the each block -->
  </table>                                                      <!-- close off the table -->
  <p> <%= link_to 'Create new To-Do item', new_todo_path %> </p>
</div>

app/views/todos/new.html.erb
<div align="center">
  <h3> Create a new To-Do list item </h3>

  <% if @todo.errors.any? %>                              <!-- check if any errors present -->
    <h3> Your To-Do item could not be saved: </h3>       <!-- if yes, display the messages -->
    <ul>
      <% @todo.errors.full_messages.each do |msg| %>       <!-- for all @todo err messages -->
        <li> <%= msg %> </li>                                 <!-- display message in list -->
      <% end %>
    </ul>
  <% end %>

  <%= render 'form' %>                                         <!-- no path necessary here -->

  <p> <%= link_to 'Cancel', todos_path %> </p>
</div>

app/views/todos/show.html.erb
<div align="center">
  <h3> To-Do item: <%= @todo.id.to_s %> </h3>
  <p> Name: <%= @todo.name %> </p>
  <p> Description: <%= @todo.description %> </p>

  <p>
    <%= link_to 'Edit this item', edit_todo_path(@todo) %> <!-- pass obj from controller -->
    |  <%= link_to 'Back to To-Do list', todos_path %>       <!-- don't need to pass obj -->
    | <%=
      link_to 'Delete this item',
      todo_path(@todo),
      method: :delete,
      data: {confirm: 'Are you sure?'}
    %>
  </p>
</div>